from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path


_PACKAGE_FILES = {
    "manifest": "manifest.json",
    "script": "script.json",
    "scenes": "scenes.json",
    "captions": "captions.json",
    "assets": "asset-manifest.json",
}


class RemotionRunner:
    def __init__(
        self,
        *,
        video_dir: Path = Path("video"),
        npx: str | None = None,
    ) -> None:
        self.video_dir = Path(video_dir)
        self.npx = npx or shutil.which("npx") or "npx"

    def command(self, package_dir: Path, composition: str, out: Path) -> list[str]:
        package_root = Path(package_dir).resolve()
        output = Path(out).resolve()
        props_path = package_root / "remotion-props.json"
        return [
            self.npx,
            "remotion",
            "render",
            "src/index.ts",
            composition,
            str(output),
            f"--public-dir={package_root}",
            f"--props={props_path}",
            "--codec=h264",
            "--audio-codec=aac",
        ]

    def _write_props(self, package_dir: Path) -> Path:
        root = Path(package_dir).resolve()
        props_path = root / "remotion-props.json"
        if all((root / name).is_file() for name in _PACKAGE_FILES.values()):
            payload = {
                "pkg": {
                    "root": str(root),
                    **{
                        key: json.loads((root / name).read_text(encoding="utf-8"))
                        for key, name in _PACKAGE_FILES.items()
                    },
                }
            }
        else:
            # Command/unit tests may use an empty package directory. Real render packages
            # are generated by app.rendering.package and always take the branch above.
            payload = {"packageDir": str(root)}
        props_path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")
        return props_path

    def render(self, package_dir: Path, composition: str, out: Path) -> Path:
        package_root = Path(package_dir).resolve()
        if not package_root.is_dir():
            raise FileNotFoundError(f"Render package directory not found: {package_root}")

        output = Path(out).resolve()
        output.parent.mkdir(parents=True, exist_ok=True)
        self._write_props(package_root)
        command = self.command(package_root, composition, output)
        result = subprocess.run(
            command,
            cwd=self.video_dir.resolve(),
            shell=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )
        if result.returncode != 0:
            log_path = output.parent / "remotion-render.log"
            log_path.write_text(
                "COMMAND\n"
                + " ".join(command)
                + "\n\nSTDOUT\n"
                + (result.stdout or "")
                + "\n\nSTDERR\n"
                + (result.stderr or ""),
                encoding="utf-8",
            )
            stdout_tail = (result.stdout or "").strip()[-2000:]
            stderr_tail = (result.stderr or "").strip()[-4000:]
            details = "\n".join(
                part
                for part in (
                    f"STDERR:\n{stderr_tail}" if stderr_tail else "",
                    f"STDOUT:\n{stdout_tail}" if stdout_tail else "",
                )
                if part
            )
            suffix = f"\n{details}" if details else ""
            raise RuntimeError(
                f"Remotion render failed with exit code {result.returncode}; "
                f"see {log_path}{suffix}"
            )
        if not output.is_file():
            raise RuntimeError(f"Remotion reported success but did not create {output}")
        return output
